language: node_js
env:
  secure: "BiZIDCtOy40/9O/h2RpIDoFEW/2AFDcGfnF0UzS446IgUcC2+J7fysw9s4Qqw5mEIFb9eANrEtOWz+hzZLdtRfl0W4JIc0O1UtOHQ67fUV8/quyymKCSWk4NyxA1IZ+KOcMOXQezVxZbkv/Bcu/9PLJaEvlB3x33VBCs95a5oq3L02CgB2rDj0slMlCqoH+kjfheQjE2B6S6qBTEnAwqteMTuYNkamQXtGuSC9UmtyY5gjyXFXF/GroxdaWuNHCKqtcYs3HovtnSWDjcUH5JVMtCwqQ0r3feUWqE6xk6HOioisrykauujDqBVHDPRw6ZSklFjGoE78tXWmTblgH0cgTEhEDxsFosMhQM0jIy6+qjPJFp4dQaUUCiqwNGWDy1ugmtwc7ml4Nb6zcdNUtEf2Erfo8sZPn0CPqscf9ViaXzLutu1/pXJaF30qe0KzeI+yvVVCa6BSxPhEcykMZYw+YMY2ewynIWMkUWis5zkYoRkpoAEfRvoZgROW6VybbDvrU/oFbdT60gSDHqpvu7zQqsrYJ2IGabkYTbgoI/AwwiII0YSmSBxN6ZfsGmTPiT1n9d02pddMsIDXsSYExhiE3ESABkCe+GdJWgx9s8Yby4kgZ3zpCkQaaag76EQlBNiZdTb1z2mX6CpXrKNXX7F+ODkGg1Ma9AfJtW3B9HaWQ="

node_js:
- stable
before_script:
- chmod +x ./scripts/sonar-runner.sh
- ./scripts/sonar-runner.sh
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
before_deploy:
- echo "building aera"
- chmod +x ./scripts/build.sh
- ./scripts/build.sh
- "/tmp/sonar-runner/sonar-runner-2.4/bin/sonar-runner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=http://sonar.gadevs.ga/ -Dsonar.projectKey=ga.hellfish:aera-client -Dsonar.projectName=AERA -Dsonar.projectVersion=0.1 -Dsonar.sources=."

deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: oVgWSSMDz7QcmuLBlGkCYuWNJtzkPX3EvbqgaCLaDeOY9zCsYY5Kq7c8K/9Uh3NnALP2uUlWy6BqMPKvvSY8b6Iu3/ZG1/LwxONXqVy0tS7lmiWY4aJqeQBFKhI7M3nGCtr51eBWvHC122gB4LsxZ4dxAjett6OKHCdmmgHIFGnm7e5S1GiCG3WgqBFBmeP5JWxA5agKjOcWpgybCOZTnShxCLYw6vhbZyeFDjcivWLRJicT7H9L9tib81t1pzPF95ralwc5EmZGSU/6cDdQcRt/OWVgW6qbMUAbxoiZiA/Bvdz3Gwkf7NhMTvW52GFQTwwtg41BmB9zvEGNw434bshvp7dtTj1TiJWYlA4A6l7FJqFbc21xVaHycJdZe+DuPZepYRxkkgn7oo0by2kbMiz1iF3roJ1F3tqGpaOVRaRKSwL9nggrvw5MVXMFrWQM8og0OF45j+YgXWUGEMA1x/NgEChxZabFfEWv3h1KZpKYqUXALXko18xn03V7MUwtSgKr/haUDLQaeoYa0g3wb0aocOlN/4EfPI2UXBV02Oj2LLtiGOnf7o8zQKcBfnu++N6NV1xaqS0mU/kMcbEBE8arin2JfckL1r5V8WLXA0TiFImGI6hJ18PCHGd7R9zLlwzU1vbST1wjNYH7omWcLEsyrp2h2zzNvFfxDhgNqDM=
    bucket: smallest-bucket-in-history
    local_dir: release
    upload_dir: aera-client
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: oVgWSSMDz7QcmuLBlGkCYuWNJtzkPX3EvbqgaCLaDeOY9zCsYY5Kq7c8K/9Uh3NnALP2uUlWy6BqMPKvvSY8b6Iu3/ZG1/LwxONXqVy0tS7lmiWY4aJqeQBFKhI7M3nGCtr51eBWvHC122gB4LsxZ4dxAjett6OKHCdmmgHIFGnm7e5S1GiCG3WgqBFBmeP5JWxA5agKjOcWpgybCOZTnShxCLYw6vhbZyeFDjcivWLRJicT7H9L9tib81t1pzPF95ralwc5EmZGSU/6cDdQcRt/OWVgW6qbMUAbxoiZiA/Bvdz3Gwkf7NhMTvW52GFQTwwtg41BmB9zvEGNw434bshvp7dtTj1TiJWYlA4A6l7FJqFbc21xVaHycJdZe+DuPZepYRxkkgn7oo0by2kbMiz1iF3roJ1F3tqGpaOVRaRKSwL9nggrvw5MVXMFrWQM8og0OF45j+YgXWUGEMA1x/NgEChxZabFfEWv3h1KZpKYqUXALXko18xn03V7MUwtSgKr/haUDLQaeoYa0g3wb0aocOlN/4EfPI2UXBV02Oj2LLtiGOnf7o8zQKcBfnu++N6NV1xaqS0mU/kMcbEBE8arin2JfckL1r5V8WLXA0TiFImGI6hJ18PCHGd7R9zLlwzU1vbST1wjNYH7omWcLEsyrp2h2zzNvFfxDhgNqDM=
    bucket: smallest-bucket-in-history
    key: aera-client/aera.zip
    bundle_type: zip
    application: aera-client
    deployment_group: aera-client_dev
    region: ap-southeast-2
    on:
      branch: master
