language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: CAoi5kLlOpdqGEhwpVw72zZPx8zqBfi30Fx6B1nBIf0T1iVj6lJZachHkdtPTjDAHA2ICfXUkFuLPT/rQHJKAQbxZpIvku6RmDrZodGX7nEIReS2kp3XpqUzw3D0KxxBQ0xtuENaulfh3nAYzvkENnpv/76Q+Bh/TTFatdXyK3a7HMZYThwmCwcQsl4zaRmLD6fM2oiyKg72TmXu84coUG+TIssqmqC1e/MaoAz9MddftWRnSUoj360zT34+EQIAjJEwt8c8/4wECs2qU/erG6YKduL7xjYkBUsci9zvzUyhsRGjuVI0cxciZyWuml5lAKvFEs5cGgUpni+/iXj3QuxbqfcICNBIm+ZjcAyJ9xHD9W1ExGYLkkPI5aPlsnFfel0Mo58NaPtJLOmpvBwXpSB1dGW4QAOVWVxnwExh2VDvYemNQX7nwmdIQ4b4agrKJuneldJMOvSStzwZmg7rO4zPdPKD1FD1eyxRJT/AWSaJEmwu2lGSmN74Wpd9zvQ8Kkj96xRW87PxeVu2PbG4zfQlJyK8cIjdrnaBai9FfJ2RP8zeO8eF9dQDRgKK3Z+gJ3h3v8HTj4N/aRGBIutPM2qRmorzSoncIKd6M6WbX40ubskg/dKsMTdHaIzdOgyyIPhQs1+zrJHaUBoQeiHRR4Zw8u+ZQHZa1y3ZShblUeg=
    bucket: smallest-bucket-in-history
    local_dir: release
    upload_dir: aera-client
    skip_cleanup: true
    on:
      branch: master
