language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: gMz1PDBpydv+fzFjolGjLv1y+VHUpdiCapfZXGFoRsQeiNfAVJVHXZ3mrhY+kwFDXoLZlYJZQvj3ZQCOBfHxbqhOXhK2qRMKOXE2ELjdDs4DteVAy9wdL8r3n7hV10LTtb7R23yQOhhW05BhA98XvlXWckSvBT8p6E21rSP/pBVLSwc75mewetgDy0/smgi2Zvq4A/T7bOc8fQUI4hIs6+aNa5vy9thA89emeOAAs0J7ehyx5vD23MdJHq2WwFuUVhWmaavMsjqTedB22wn6KZ+2kUSNKNANCg+zXBrChWfMKlI4A2biY2dluEZ144auCNnch2nYt3rAJPvoH6X6GiQ+ri/SbkyHMKVoLPgexBUbL4iwyLTVRzvMEhcgm+0ibhMdZsNO8GzArNuPjWgz13O8BKQgOtquvyKyZ/83DIahnt1AfqjGXEJwYIxlVHhS/kff5aHqYj+thujIKx08C3s70nRZYuNMBIRMxg7kefrmLYtlvN57nFIwbPsDU/LlJfAmWlrUA5p0mSuEBaep0Pij04b06WFaJqL5DO3aunllTqoxzJ1KZEQ734YAA78CPFS+r7V3Nki+kb8Z812qw4zrZj+/0VNafSaDONpOZwlST0lipwJ8WfqeV6f9w+OtAmX/3o1QBHDjSnX86BUpjGIT9speE4vqIB/9NO50Rr0=
    bucket: smallest-bucket-in-history
    local_dir: release
    upload_dir: aera-client
    skip_cleanup: true
    on:
      branch: master
