language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
- provider: s3
  region: ap-southeast-2
  access_key_id: AKIAJWQDSHMR5J6IN7NA
  secret_access_key:
    secure: "PF99AXYUgwm2iW+z+nMJGRTIKxVCJZGp3QgAvptjh1/0eqh0Ak7Y2Jka5Jnat1gi0TeQIkfW6JAnTK2wGq+o5rb9lbK8tJyGSZz7OixTsqoXvsBWY1LDVH0A9wc3AEKMiLhnfnjmQtX+u2MoCsYjh38VFZy+Hm9tAdH/bYGm8CWRhgPTNVee/7F8vv3FEHfyktzguw7WdBmzz35z9RtkrYXncu9GyvYoaweXVG3oCDy6xN724yftccYLuVrcGlNQQ9NLCIU2kSq7DQzPkqpf1qsI2ZDf7/AGJdEGDnb1ftdI+5wdRQavMtaYnpQSS3R/QJSHjgb1XKfN0tqlTGiSmZaMt4mU27pOGsVIqQQHS6/yVEQrKfJ0PaF53HGEUHkiFsPVebdilhDvFAjmUCaUpWir3mMnil5AGZnAU3x41ODupem4iONv8zd5rI1zdDjXt1fd1lbjiMVt5wPhpoNCMkOOI885ENPa8bw0Hvt5k/caDfwZxg/ExmnbkFhy3BcnHGGGUT0c1aPRHPJJNc2gx9u4JZh4WEMcerN7MeH8+s/vlepkRZUcDB7maMm0MI/m1fgD3rR/t1Krx+gJFximcVpAnWPPqbwA
  bucket: smallest-bucket-in-history
  local_dir: release
  upload_dir: aera-client
  skip_cleanup: true
  on:
    branch: master
