language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
- provider: s3
  region: ap-southeast-2
  access_key_id: AKIAJWQDSHMR5J6IN7NA
  secret_access_key:
    secure: Gqz+qf3hUKp3/7WQ3WgVHuO4LKqqHi5bpmMj0ycik/0rRSBIHsqJ8mlH4MQnY/BR+l9CusbeWTihOGtEvgMjPNTV7fCXz0EkvETuUrAyRttBsPG0HuHio5YkOH0TeyHDOvorkgKa2pV2XejWYoZ20O9+bvzL1NFYF268hysFJys2uAzjaA6bR580Cin/yJgEFM2eT2bVdP+j8hUkdDdnvHJpQQRlALwYWH1DJAoTqPv+WGQmufkM+LbLGLPm9jgNIP52g3W+BAXUPalcEwX2Oz4l9Mw/VXO2XnTHRTUUPUUo43fck445BcGPKMD38e1N7R1+UFe3fXp9j/vPLvQ3k88hYLLcklB63K48k7rmFZaFqPCkDr/AyPE0IVvfjTkA94D/wI8l7Rk/l40uJ8WrA9goBXo53+V0j6zRI+juGAwI6JLXs/H/JA1tgP7ztrcj0JN1LtBtsn6wCGl3s1Jb0hTQkJi8PYe72xsSGWKHgxHlehVn3izo/qjG3j1ajgn+xiKcxyDmx3wo9CVV6DE7Ujluy9R2dtsFNgZjSTINQUdZykp+SWjMbOufM+UFrwVv5BFQ5iFJasyFCIYleQmIK3uyXw0MOx4M1HxanIZzhLarloS2hechPp12qM1UsvFfg8EezrzecMmfW1PaMXWf11pY3RdZftXGSCM9EPHLmg8=
  bucket: smallest-bucket-in-history
  local_dir: release
  upload_dir: aera-client
  skip_cleanup: true
  on:
    branch: master
