language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
  matrix:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: ZA5g3VGNONSm+OdaHT4Y2GMPbn96LGG+pbVFKwbaPJS3LBmzI1sdmBEb8Jv2Yk4/w1vp/iIPVuJFNwTCeFJKu63rvwgIdVppc7+rzdFsGfCgUP8dNGNDvT8w43hH9CJLeoAgbub8gq60Ib5IYhbulWu0cp36geMVTrMJgHWZ612AUtmLTqjTg1LxzVw43sJDct7i9ldBXzYJHc0E/tE9NpUiT8S7yrImYxMg5HxY5FqMffslCakrGE4X1kXcahiFUv9MIolYIpMNbR3qusnTB2q/14z4bx0jbWubKcmqUuQMQ9va2sYr0yArMiW2a8V0ww9T1Lodm9ijc9kXPliMMSTUTY5tBtIRUSmMAWsxfNKHZiS0+91FycLko9yYkUWSNDYzLVMpA5Jn/Nl8HLXG3iK7rcoM41ePanh5CB77NAXbSZnpwZ6SaJPyKE/XuNqcOaHjzp0InYnh6InpFKlMskG1hA3GJF6dQd2MHn9Lk4n4KBfp3j9VfytY03iNZgWuClhpVr2zWW1E/qalJX4qdRD3Mw73ZW/QYluEIaKpkZe48/Rv49TnYbKLyXf/9RV3zYpMt+XqKyvT9bzjLpxeiTpCzlW84ajk+Cbp+3BdJRty4XAxleNFWjsCwl8u/4pCyqqIvJrovykjAhxMZ5uqZPD3x/q4Jn9o2Q860FKnKMw=
    bucket: smallest-bucket-in-history
    local_dir: release
    upload_dir: aera-client
    skip_cleanup: true
    on:
      branch: master
