language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJWQDSHMR5J6IN7NA
    secret_access_key:
      secure: Zpi/ID+2gpYnx1IlYPsszCk1s5sRjBQZ5EKKWwC0dtgzoSB0lepfmbazZjN4KhvDrClfWP1UOZwS+1eDbYRYPW6boZsvQaY51Elk8Et/CKs9GOwpRoHqC0mG4kPwb48eTWsf0Za8/AVaoLgrazegJIemrL/cD0Mrh7sPQmLelueaTUqPfDG20n50duwjWeQO/SV0mn5JueKN3JLwsj8XQfVvQcnKHYiZO5/I9RVzpdpTmfnUnxAdEylylpRArln5XDhgFENRwR2Jz01Zvby9xIKZtMiTQ032YF9DrzL00RRDCqai8PMKojVSe3wycKLULjoV9NgJM+UEKFjvOdT9kZXMr917gKZV0kFc5prcaz9hYs/48lu5+XDnk0f8EkywK/eDfxrq9XDjjclQ2KF1j/RpZtZgcSjbkROzyTau49gotO6M4KtwFwm//roZV87ETvX65VvE2crxYMonji1wbR77czywl9gphIMtRc0n8r1YZRZyxyOvQfFE2AoMrVOAMFy3dy03u81rSNdOfrejq6XM17AntrPgODcZB07SbcaOp7QnwerU7Cuqd2hoJQaDhjGwTV9KdyBs4TKy3AaUgbi3ogc9J51HVjuSLLAT2g1tKmgpuwzGM77DyoyezUutGfpogPrxOkiyxcQJC8frvuq1M1I43B6Fix4HfrU4MMg=
    bucket: smallest-bucket-in-history
    local_dir: release
    upload_dir: aera-client
    skip_cleanup: true
    on:
      branch: master
