language: node_js
node_js:
- stable
before_deploy:
- echo "building aera"
- chmod +x ./travis/build.sh
- ./travis/build.sh
deploy:
- provider: s3
  region: ap-southeast-2
  access_key_id: AKIAJWQDSHMR5J6IN7NA
  secret_access_key:
    secure: Gqz+qf3hUKp3/7WQ3WgVHuO4LKqqHi5bpmMj0ycik/0rRSBIHsqJ8mlH4MQnY/BR+l9CusbeWTihOGtEvgMjPNTV7fCXz0EkvETuUrAyRttBsPG0HuHio5YkOH0TeyHDOvorkgKa2pV2XejWYoZ20O9+bvzL1NFYF268hysFJys2uAzjaA6bR580Cin/yJgEFM2eT2bVdP+j8hUkdDdnvHJpQQRlALwYWH1DJAoTqPv+WGQmufkM+LbLGLPm9jgNIP52g3W+BAXUPalcEwX2Oz4l9Mw/VXO2XnTHRTUUPUUo43fck445BcGPKMD38e1N7R1+UFe3fXp9j/vPLvQ3k88hYLLcklB63K48k7rmFZaFqPCkDr/AyPE0IVvfjTkA94D/wI8l7Rk/l40uJ8WrA9goBXo53+V0j6zRI+juGAwI6JLXs/H/JA1tgP7ztrcj0JN1LtBtsn6wCGl3s1Jb0hTQkJi8PYe72xsSGWKHgxHlehVn3izo/qjG3j1ajgn+xiKcxyDmx3wo9CVV6DE7Ujluy9R2dtsFNgZjSTINQUdZykp+SWjMbOufM+UFrwVv5BFQ5iFJasyFCIYleQmIK3uyXw0MOx4M1HxanIZzhLarloS2hechPp12qM1UsvFfg8EezrzecMmfW1PaMXWf11pY3RdZftXGSCM9EPHLmg8=
  bucket: smallest-bucket-in-history
  local_dir: release
  upload_dir: aera-client
  skip_cleanup: true
  on:
    branch: master
secret_access_key:
  secure: cYHABqL/7dd4WmiA3bvOgCpohpW9cm79t7AlW5MZyGA24Iww7+FiyqBDCn4IHKMWEkx+2/bkQtm38qpziHTrYB+gsBZ3Ih67JfqU1hbh2uUqiBbuKaxO43UIiJ8TgZ3Y1t2CYy/t6g+QncOmQgSaD7d3IeAgTy+2QIxcvL82lLRd5W50482aFli4Pmr+Xs3d7CsEcExjeWSDVVq7kxCZKONYJM8aQzpoaHym2bxCw03nRuTL7ZkvbEntPNZusskM0S+E0U5mU8UhtMmDtYB5esQa657zoTkL4NbTNxNdJy6S9eCMMO/q+r34VPKgNyOKOB1YG56ke40TtnOjFk/kqZxwSWfJlg/40zUXKFk3UQNE9hH/xlMOzkt0LqTl831BBtZ0bZILvKDZlvSHz51R+xPzt9tMcmJMGoZNgFyJYEou6BvvEtRCzzcgMYsMkon2CCYF9Nj8mlmicyCHqMW6aUxcoHv1yO5otTdq69C5dUmKYlRgS3RUeuNBsUodsklT6dw612H1awRr987iM5g+QArV8PBsddWT7vrJ+q018Dh/ZU2omP0zVSjO0imvB1WzvYSDfgJmMboYVIUQFaVr7oAzrFPzNsdAS3apXPVbpAR6erlLgocUDG0fu39GQ0yu5ftXDmWgUT8OdJd3CNv1ann+UKn5k0LqvZhIqEf0rBU=
